language: ruby
rvm:
  - 2.6.1

before_install:
  # Federalist requires bundler version 1
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'

script: ./travis_scripts/build.sh

env:
  global:
    # This speeds up the installation of html-proofer
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

addons:
  apt:
    packages:
      # We need this to check https links
      - libcurl4-openssl-dev

# Caching bundler gem packages will speed up the build
cache: bundler
