# OpenGraph / Twitter metadata
title: DHS Binding Operational Directives
small_title: DHS Binding Operational Directives
smallest_title: DHS BODs
description: Binding Operational Directives from the Department of Homeland Security
name: Binding Operational Directives and implementation guidance

report_url: "/assets/report/bod-18-01.pdf"

# GA and GitHub
google_analytics_ua: ua-33523145-2
org_name: dhs-ncats
repo_name: cyber.dhs.gov
branch: master

uswds_path: assets/vendor/uswds

exclude:
- CONTRIBUTING.md
- _config.yml
- .travis.yml
- .gitignore
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- vendor
- gulpfile.js
- manifest.yml
- package.json
- Staticfile
- Staticfile.auth
- node_modules
- .nvmrc
- .sass-cache
- todo.txt

markdown: kramdown

plugins:
  - jekyll-redirect-from

kramdown:
  input: GFM
  syntax_highlighter: rouge

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

collections:
  pages:
    output: true
    permalink: /:path/
