# OpenGraph / Twitter metadata
title: Enhance Email and Web Security
small_title: Enhance Email & Web Security
smallest_title: Email & Web Security
description: Binding Operational Directive 18-01 - Enhancing Email and Web Security
name: BOD 18-01

report_url: "/assets/report/bod-18-01.pdf"

# GA and GitHub data
google_analytics_ua: ua-33523145-2
org_name: dhs-ncats
repo_name: cyber.dhs.gov
branch: master

uswds_path: assets/vendor/uswds

exclude:
- CONTRIBUTING.md
- _config.yml
- .travis.yml
- .gitignore
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- vendor
- gulpfile.js
- manifest.yml
- package.json
- Staticfile
- Staticfile.auth
- node_modules
- .nvmrc
- .sass-cache
- todo.txt

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

collections:
  pages:
    output: true
    #permalink: /:path/
